### ISSUE TITLE
DOC: suggestion for improved clarity

### ISSUE THREAD

**Issue by keithbriggs** [erelsgl/cvxpy_leximin#1]
Currently the readme says:
`
The [cvxpy](https://github.com/cvxpy/cvxpy)_leximin package extends cvxpy by adding support for optimization in [leximin order](https://en.wikipedia.org/wiki/Leximin_order). It adds the Leximin objective, which takes several expressions as arguments. Solving a problem with the Leximin objective aims to maximize the smallest objective; subject to this, the next-smallest objective; and so on.`

This is confusing, because it is not defined how "the smallest objective" relates to the "several expressions".   Is each expression an objective?  If so, don't use two different words for the same thing.  Also, "subject to this" needs a proper definition - does it mean that if two or more smallest objectives have equal maximum values, then the next-smallest are compared (and so on)?

**Comment by erelsgl** [comment]
Thanks. I have elaborated the readme. Is it clearer now?

**Comment by keithbriggs** [comment]
Yes - much better, except for the bit:

`Note that the current implementation works only when domain (as defined by the constraints) is convex. In particular, it does not work for integer programming.`

In the definition of the problem, nothing has been mentioned about constraints.   And is the above statement strictly true, or is it really the stronger case that the constraints must be constructable using DCP rules?

**Comment by erelsgl** [comment]
I added that maximization is subject to the constraints (as in every optimization problem).

Regarding the second question: the correctness proof of the algorithm requires that the domain is convex (that is: the convex combination of any two feasible solutions is feasible). It does not require that the constraints are constructible using DCP rules.

**Comment by keithbriggs** [comment]
Thank you!  For me, it's all much clearer now.
